// ============================================================
// data.js
// Defines what a "manhole sensor reading" looks like, and the
// prototype math that turns a raw distance into a blockage
// percentage and a status. This file has NO knowledge of the UI —
// it only knows about the data shape, so it can later be swapped
// for a real FastAPI/Firebase/WebSocket source without touching
// any component code.
// ============================================================

// Prototype thresholds — deliberately easy to find and tweak.
export const THRESHOLDS = {
  WARNING: 30, // >= 30% estimated blockage => WARNING
  CRITICAL: 60, // >= 60% estimated blockage => CRITICAL
};

// Fixed locations are part of each manhole record, not generated by the map.
// A backend can replace this catalog by supplying the same fields per node.
const MANHOLE_LOCATIONS = [
  ["Riverside Park", 17.3854, 78.4869],
  ["Market Street", 17.3881, 78.4912],
  ["West Zone", 17.3817, 78.4798],
  ["Lake View Road", 17.3925, 78.4826],
  ["Old City", 17.3616, 78.4747],
  ["Banjara Hills", 17.4156, 78.4347],
  ["Jubilee Hills", 17.4326, 78.4071],
  ["Secunderabad", 17.4399, 78.4983],
  ["Tank Bund", 17.4239, 78.4738],
  ["Begumpet", 17.4435, 78.4624],
  ["Ameerpet", 17.4375, 78.4483],
  ["Kukatpally", 17.4849, 78.4138],
  ["Madhapur", 17.4483, 78.3915],
  ["Gachibowli", 17.4401, 78.3489],
  ["Charminar Area", 17.3634, 78.481],
  ["Abids", 17.3933, 78.4731],
  ["Himayatnagar", 17.4062, 78.4898],
  ["Nampally", 17.3935, 78.4654],
  ["Sainikpuri", 17.4857, 78.5421],
  ["Riverside Park", 17.3792, 78.4894],
  ["Market Street", 17.3916, 78.4958],
  ["West Zone", 17.3775, 78.4761],
  ["Lake View Road", 17.3988, 78.4805],
  ["Old City", 17.3548, 78.4672],
  ["Banjara Hills", 17.4092, 78.4421],
  ["Jubilee Hills", 17.4264, 78.4148],
  ["Secunderabad", 17.4471, 78.5014],
  ["Tank Bund", 17.4165, 78.4789],
  ["Begumpet", 17.4512, 78.4586],
  ["Ameerpet", 17.4298, 78.4527],
  ["Kukatpally", 17.4976, 78.3997],
  ["Madhapur", 17.4598, 78.3857],
  ["Gachibowli", 17.4348, 78.3569],
  ["Charminar Area", 17.3684, 78.4792],
  ["Abids", 17.3985, 78.4698],
  ["Himayatnagar", 17.4128, 78.4952],
  ["Nampally", 17.3867, 78.4613],
  ["Sainikpuri", 17.4774, 78.5516],
  ["Riverside Park", 17.3718, 78.4822],
  ["Market Street", 17.3857, 78.5011],
  ["West Zone", 17.3694, 78.4705],
  ["Lake View Road", 17.4021, 78.4877],
  ["Old City", 17.3479, 78.4728],
  ["Banjara Hills", 17.4218, 78.4478],
  ["Jubilee Hills", 17.4391, 78.4204],
  ["Secunderabad", 17.4315, 78.5102],
  ["Tank Bund", 17.4098, 78.4691],
  ["Begumpet", 17.4568, 78.4693],
  ["Ameerpet", 17.4464, 78.4408],
  ["Kukatpally", 17.4752, 78.4267],
  ["Madhapur", 17.4417, 78.4008],
  ["Gachibowli", 17.4514, 78.3397],
  ["Charminar Area", 17.3542, 78.4816],
  ["Abids", 17.3879, 78.4796],
  ["Himayatnagar", 17.3994, 78.4842],
  ["Nampally", 17.4007, 78.4578],
  ["Sainikpuri", 17.4941, 78.5337],
  ["Riverside Park", 17.3946, 78.4753],
  ["Market Street", 17.3759, 78.4971],
  ["West Zone", 17.3868, 78.4662],
  ["Lake View Road", 17.4102, 78.4714],
];

/**
 * Estimated Blockage % = (1 - measuredDistance / expectedPipeLength) x 100
 * This is a PROTOTYPE estimation, not a validated physical measurement —
 * hence "Estimated Blockage" everywhere in the UI rather than an exact claim.
 */
export function calculateBlockage(expectedPipeLength, measuredDistance) {
  const raw = (1 - measuredDistance / expectedPipeLength) * 100;
  return Math.max(0, Math.min(100, Math.round(raw)));
}

export function calculateStatus(blockagePercentage) {
  if (blockagePercentage >= THRESHOLDS.CRITICAL) return "CRITICAL";
  if (blockagePercentage >= THRESHOLDS.WARNING) return "WARNING";
  return "CLEAR";
}

function pad(n, width) {
  return String(n).padStart(width, "0");
}

function randomBetween(min, max) {
  return Math.random() * (max - min) + min;
}

/**
 * Builds the initial fleet of manholes. Statuses are seeded so the
 * dashboard opens on a realistic-looking city (mostly clear, some
 * warning, a handful critical) rather than pure random noise.
 */
export function generateManholes(count = 60) {
  if (count > MANHOLE_LOCATIONS.length) {
    throw new Error(
      `Only ${MANHOLE_LOCATIONS.length} manhole locations are configured`,
    );
  }
  const buckets = [
    { status: "CLEAR", n: Math.round(count * 0.7), min: 0, max: 25 },
    { status: "WARNING", n: Math.round(count * 0.2), min: 32, max: 55 },
    {
      status: "CRITICAL",
      n: count - Math.round(count * 0.7) - Math.round(count * 0.2),
      min: 62,
      max: 88,
    },
  ];

  const letters = ["A", "B", "C", "D"];
  const manholes = [];
  let nodeNum = 1;

  buckets.forEach((bucket) => {
    for (let i = 0; i < bucket.n; i++) {
      const expectedPipeLength = Math.round(randomBetween(80, 120));
      const blockagePercentage = Math.round(
        randomBetween(bucket.min, bucket.max),
      );
      const measuredDistance = Math.round(
        expectedPipeLength * (1 - blockagePercentage / 100),
      );
      const [zone, latitude, longitude] = MANHOLE_LOCATIONS[nodeNum - 1];
      const idNum = pad(nodeNum, 2);
      const letter = letters[nodeNum % letters.length];

      manholes.push({
        id: `MH${pad(nodeNum, 3)}`,
        nodeId: `NODE_${idNum}${letter}`,
        manholeId: `MANHOLE_${idNum}${letter}`,
        name: zone,
        area: zone,
        latitude,
        longitude,
        expectedPipeLength,
        measuredDistance,
        blockagePercentage: calculateBlockage(
          expectedPipeLength,
          measuredDistance,
        ),
        status: calculateStatus(
          calculateBlockage(expectedPipeLength, measuredDistance),
        ),
        lastUpdated: Date.now(),
        sensorId: `US-${idNum}${letter}`,
        history: [],
      });
      nodeNum++;
    }
  });

  // Give every manhole one seed history point for its sparkline.
  manholes.forEach((m) => {
    m.history.push({
      t: Date.now(),
      distance: m.measuredDistance,
      blockage: m.blockagePercentage,
    });
  });

  return manholes;
}
