// ============================================================
// data.js
// Defines what a "manhole sensor reading" looks like, and the
// prototype math that turns a raw distance into a blockage
// percentage and a status. This file has NO knowledge of the UI —
// it only knows about the data shape, so it can later be swapped
// for a real FastAPI/Firebase/WebSocket source without touching
// any component code.
// ============================================================

// Prototype thresholds keyed to the final Risk Score.
export const THRESHOLDS = {
  WARNING: 31,
  CRITICAL: 61,
};

function clampNumber(value, min = 0, max = 100) {
  const safe = Number(value) || 0;
  return Math.max(min, Math.min(max, safe));
}

// Fixed locations are part of each manhole record, not generated by the map.
// A backend can replace this catalog by supplying the same fields per node.
const MANHOLE_LOCATIONS = [
  ["Riverside Park", 17.3854, 78.4869],
  ["Market Street", 17.3881, 78.4912],
  ["West Zone", 17.3817, 78.4798],
  ["Lake View Road", 17.3925, 78.4826],
  ["Old City", 17.3616, 78.4747],
  ["Banjara Hills", 17.4156, 78.4347],
  ["Jubilee Hills", 17.4326, 78.4071],
  ["Secunderabad", 17.4399, 78.4983],
  ["Tank Bund", 17.4239, 78.4738],
  ["Begumpet", 17.4435, 78.4624],
  ["Ameerpet", 17.4375, 78.4483],
  ["Kukatpally", 17.4849, 78.4138],
  ["Madhapur", 17.4483, 78.3915],
  ["Gachibowli", 17.4401, 78.3489],
  ["Charminar Area", 17.3634, 78.481],
  ["Abids", 17.3933, 78.4731],
  ["Himayatnagar", 17.4062, 78.4898],
  ["Nampally", 17.3935, 78.4654],
  ["Sainikpuri", 17.4857, 78.5421],
  ["Riverside Park", 17.3792, 78.4894],
  ["Market Street", 17.3916, 78.4958],
  ["West Zone", 17.3775, 78.4761],
  ["Lake View Road", 17.3988, 78.4805],
  ["Old City", 17.3548, 78.4672],
  ["Banjara Hills", 17.4092, 78.4421],
  ["Jubilee Hills", 17.4264, 78.4148],
  ["Secunderabad", 17.4471, 78.5014],
  ["Tank Bund", 17.4165, 78.4789],
  ["Begumpet", 17.4512, 78.4586],
  ["Ameerpet", 17.4298, 78.4527],
  ["Kukatpally", 17.4976, 78.3997],
  ["Madhapur", 17.4598, 78.3857],
  ["Gachibowli", 17.4348, 78.3569],
  ["Charminar Area", 17.3684, 78.4792],
  ["Abids", 17.3985, 78.4698],
  ["Himayatnagar", 17.4128, 78.4952],
  ["Nampally", 17.3867, 78.4613],
  ["Sainikpuri", 17.4774, 78.5516],
  ["Riverside Park", 17.3718, 78.4822],
  ["Market Street", 17.3857, 78.5011],
  ["West Zone", 17.3694, 78.4705],
  ["Lake View Road", 17.4021, 78.4877],
  ["Old City", 17.3479, 78.4728],
  ["Banjara Hills", 17.4218, 78.4478],
  ["Jubilee Hills", 17.4391, 78.4204],
  ["Secunderabad", 17.4315, 78.5102],
  ["Tank Bund", 17.4098, 78.4691],
  ["Begumpet", 17.4568, 78.4693],
  ["Ameerpet", 17.4464, 78.4408],
  ["Kukatpally", 17.4752, 78.4267],
  ["Madhapur", 17.4417, 78.4008],
  ["Gachibowli", 17.4514, 78.3397],
  ["Charminar Area", 17.3542, 78.4816],
  ["Abids", 17.3879, 78.4796],
  ["Himayatnagar", 17.3994, 78.4842],
  ["Nampally", 17.4007, 78.4578],
  ["Sainikpuri", 17.4941, 78.5337],
  ["Riverside Park", 17.3946, 78.4753],
  ["Market Street", 17.3759, 78.4971],
  ["West Zone", 17.3868, 78.4662],
  ["Lake View Road", 17.4102, 78.4714],
];

/**
 * Obstruction score based on how far the obstruction sits from the sensor.
 * Larger distances mean less blockage; smaller distances mean more blockage.
 */
export function calculateObstructionScore(
  expectedPipeLength,
  obstructionDistance,
) {
  if (!expectedPipeLength || expectedPipeLength <= 0) return 0;
  const raw =
    ((expectedPipeLength - obstructionDistance) / expectedPipeLength) * 100;
  return clampNumber(raw);
}

export function calculateBlockage(expectedPipeLength, measuredDistance) {
  return calculateObstructionScore(expectedPipeLength, measuredDistance);
}

export function calculateWaterLevel(
  expectedPipeLength,
  measuredDistance,
  explicitWaterLevel,
) {
  if (Number.isFinite(explicitWaterLevel)) {
    return clampNumber(explicitWaterLevel);
  }
  const obstructionScore = calculateObstructionScore(
    expectedPipeLength,
    measuredDistance,
  );
  const rawWater = Math.round(obstructionScore * 0.7 + 8);
  return clampNumber(rawWater);
}

export function calculateRiskScore(obstructionScore, waterLevelPercentage = 0) {
  const safeObstruction = clampNumber(obstructionScore);
  const safeWater = clampNumber(waterLevelPercentage);
  const riskScore = safeObstruction * 0.4 + safeWater * 0.6;
  return clampNumber(riskScore);
}

export function calculateSeverityLabel(riskScore) {
  const score = clampNumber(riskScore);
  if (score >= THRESHOLDS.CRITICAL) return "High";
  if (score >= THRESHOLDS.WARNING) return "Moderate";
  return "Low";
}

export function calculateStatus(blockagePercentage, waterLevelPercentage = 0) {
  const riskScore =
    arguments.length === 1
      ? clampNumber(blockagePercentage)
      : calculateRiskScore(blockagePercentage, waterLevelPercentage);
  if (riskScore >= THRESHOLDS.CRITICAL) return "CRITICAL";
  if (riskScore >= THRESHOLDS.WARNING) return "WARNING";
  return "CLEAR";
}

function pad(n, width) {
  return String(n).padStart(width, "0");
}

function randomBetween(min, max) {
  return Math.random() * (max - min) + min;
}

/**
 * Builds the initial fleet of manholes. Statuses are seeded so the
 * dashboard opens on a realistic-looking city (mostly clear, some
 * warning, a handful critical) rather than pure random noise.
 */
export function generateManholes(count = 60) {
  if (count > MANHOLE_LOCATIONS.length) {
    throw new Error(
      `Only ${MANHOLE_LOCATIONS.length} manhole locations are configured`,
    );
  }
  const buckets = [
    { status: "CLEAR", n: Math.round(count * 0.7), min: 0, max: 25 },
    { status: "WARNING", n: Math.round(count * 0.2), min: 32, max: 55 },
    {
      status: "CRITICAL",
      n: count - Math.round(count * 0.7) - Math.round(count * 0.2),
      min: 62,
      max: 88,
    },
  ];

  const letters = ["A", "B", "C", "D"];
  const manholes = [];
  let nodeNum = 1;

  buckets.forEach((bucket) => {
    for (let i = 0; i < bucket.n; i++) {
      const expectedPipeLength = Math.round(randomBetween(80, 120));
      const blockagePercentage = Math.round(
        randomBetween(bucket.min, bucket.max),
      );
      const measuredDistance = Math.round(
        expectedPipeLength * (1 - blockagePercentage / 100),
      );
      const waterLevelPercentage = calculateWaterLevel(
        expectedPipeLength,
        measuredDistance,
      );
      const [zone, latitude, longitude] = MANHOLE_LOCATIONS[nodeNum - 1];
      const idNum = pad(nodeNum, 2);
      const letter = letters[nodeNum % letters.length];

      const obstructionScore = calculateObstructionScore(
        expectedPipeLength,
        measuredDistance,
      );
      const riskScore = calculateRiskScore(
        obstructionScore,
        waterLevelPercentage,
      );

      manholes.push({
        id: `MH${pad(nodeNum, 3)}`,
        nodeId: `NODE_${idNum}${letter}`,
        manholeId: `MANHOLE_${idNum}${letter}`,
        name: zone,
        area: zone,
        latitude,
        longitude,
        pipeLength: expectedPipeLength,
        expectedPipeLength,
        measuredDistance,
        obstructionDistance: measuredDistance,
        obstructionScore,
        blockagePercentage: obstructionScore,
        waterLevel: waterLevelPercentage,
        waterLevelPercentage,
        riskScore,
        blockageSeverity: calculateSeverityLabel(riskScore),
        status: calculateStatus(riskScore),
        lastUpdated: Date.now(),
        sensorId: `US-${idNum}${letter}`,
        history: [],
      });
      nodeNum++;
    }
  });

  // Give every manhole one seed history point for its sparkline.
  manholes.forEach((m) => {
    m.history.push({
      t: Date.now(),
      nodeId: m.nodeId,
      sensorId: m.sensorId,
      distance: m.measuredDistance,
      obstructionDistance: m.obstructionDistance ?? m.measuredDistance,
      obstructionScore: m.obstructionScore,
      blockage: m.blockagePercentage,
      blockagePercentage: m.blockagePercentage,
      waterLevel: m.waterLevelPercentage,
      waterLevelPercentage: m.waterLevelPercentage,
      riskScore: m.riskScore,
      blockageSeverity: m.blockageSeverity,
      status: m.status,
    });
  });

  return manholes;
}
